### ISSUE TITLE
Out Of China Method

### ISSUE THREAD

**Issue by hugocroch** [wdanxna/GradientPolyline#1]
Hi, I tried your demo and your code. I see that you check if the user is out of China. If the user is in China you modify the coordinates. I don't really understand why you need to do this.

Could you explain me the reason? 
Thank you.

**Comment by wdanxna** [comment]
@hugocroch well...it seems like Chinese government provide some inaccurate projection parameters or something weird trick, making the gps data never match accurate point on the map in china(about 400m bias). So if you are in china(like myself) you need to do some bias on your gps data.

**Comment by hugocroch** [comment]
Thank you very much for the explanation @wdanxna !
